### ISSUE TITLE
New dbplyr interface

### ISSUE THREAD

**Issue by stibu81** [IMSMWU/RClickhouse#92]
When I use RClickhouse 0.6.4 from CRAN I get the following warning:

```
<ClickhouseConnection> uses an old dbplyr interface
ℹ Please install a newer version of the package or contact the maintainer
```

This is due to a change in the interface that started with dbplyr 2.0.0 (see [here](https://dbplyr.tidyverse.org/articles/backend-2.html)). For now, this is just a warning and RClickhouse still works as expected, but according to the aforementioned page, the old interface will stop working around mid-2023 (12 months after the publication of version 2.2.0 in June 2022).

Do you intend to fix this in time? This would be highly appreciated.

**Comment by inkrement** [comment]
Hi Stefan, thanks for reporting! We'll take a look at it.

**Comment by stibu81** [comment]
Any news on this?

**Comment by inkrement** [comment]
@dariayudaeva already works on this task. Since there is still some time left until mid-2023, it is not our top-1 priority. Anyhow, you can track the latest changes in her fork: https://github.com/dariayudaeva/RClickhouse

**Comment by dariayudaeva** [comment]
Hi, thanks for reaching out! Overall, it should be mostly fixed by now, but we wanted to test everything again to make sure. :) Will finish soon.

**Comment by stibu81** [comment]
Thanks for the good news! As you say, there is no need for a rush, but it's good to know that you're taking care of this. Thank you for your efforts!

**Comment by tel** [comment]
Hi team, it's been a bit under a year since the last comment. I'm using package version 0.6.8 and still receiving this error. I'm curious if there's been motion here.

**Comment by inkrement** [comment]
The problem should already be fixed. If it is still incorrectly displayed in the current version, there is probably still a bug or the deployment failed. We will look into this. However, I can't say how long this will take due to the current lack of time. We would be grateful for external support.
